chiyadev/MudaeFarm

MudaeFarm/Program.cs
=> Fix maid username regex not hanling spaces between numbers

MudaeFarm/CommandListener.cs, MudaeFarm/Config.cs, MudaeFarm/DiscordLogin.cs, README.md
=> Add status command

MudaeFarm/MudaeFarm.cs
=> Ignore TYPING_START and SESSIONS_REPLACE dispatch handling errors

MudaeFarm/AutoClaimer.cs, MudaeFarm/CommandListener.cs, MudaeFarm/Config.cs, README.md
=> Add command to disable autoclaiming in a specific server

MudaeFarm/MudaeStateManager.cs
Critical bug that causes $tu to spam
=> Fix ForceNextRefresh not being toggled

MudaeFarm/Program.cs, MudaeFarm/UpdateChecker.cs
Implements auto-update functionality. Will check for new releases every startup, extract newer binaries in a temp location and overwrite itself.
=> Implement auto-update

MudaeFarm/TimersUpParser.cs
Username test was not case-insensitive.
=> Fix claim not being parsed due to username test

MudaeFarm/MudaeFarm.cs, MudaeFarm/MudaeFarm.csproj
Resolves #22 
This should solve connection issues on Windows 7, although I don't have a Windows 7 machine to test at the moment.
=> Use WebSocket4Net on Windows 7

MudaeFarm/Log.cs
=> Include time in logs

MudaeFarm/MudaeFarm.cs, MudaeFarm/Program.cs, MudaeFarm/UpdateChecker.cs
=> ZipFileExtensions.ExtractToDirectory MissingMethodException

MudaeFarm/MudaeFarm.cs
=> Automatically restart modules on failure

MudaeFarm/AutoClaimer.cs
=> Fix attempting to claim $im command output

MudaeFarm/MudaeInfo.cs
=> Fix maid regex not matching "Mudamaid" and butlers

MudaeFarm/MudaeFarm.cs, MudaeFarm/Program.cs, MudaeFarm/UpdateChecker.cs
=> Add verbose logging switch in command line

MudaeFarm/TimersUpParser.cs, README.md
=> Add support for $mu as state_update_command

MudaeFarm/AutoClaimer.cs, MudaeFarm/ConfigManager.cs, MudaeFarm/DiscordUtils.cs
=> Claim characters from other user's wishlists

MudaeFarm/AutoKakera.cs
=> Always claim purple kakera if configured

MudaeFarm/AutoClaimer.cs, MudaeFarm/AutoKakera.cs, MudaeFarm/AutoRoller.cs, MudaeFarm/ConfigManager.cs, MudaeFarm/MudaeStateManager.cs
=> Add ability to disable MudaeFarm completely using config

MudaeFarm/AutoClaimer.cs, MudaeFarm/ConfigManager.cs, MudaeFarm/Program.cs, README.md
=> Add anime specific character blacklist

MudaeFarm/AuthTokenManager.cs, MudaeFarm/MudaeFarm.csproj
=> Fix profiles not being generated correctly

MudaeFarm/CredentialManager.cs, MudaeFarm/DiscordConfigurationSource.cs
Resolves https://github.com/chiyadev/MudaeFarm/issues/134.
=> Fix aliased profiles changing selected profile

MudaeFarm/MudaeOutputParser.cs, MudaeFarm/MudaeRoller.cs
Resolves https://github.com/chiyadev/MudaeFarm/issues/131.
=> Fix not handling rolls remaining message

MudaeFarm/DiscordConfigurationSource.cs, README.md
Resolves https://github.com/chiyadev/MudaeFarm/issues/131.
=> Add support for line-separated character/anime wishlist

MudaeFarm/MudaeClaimer.cs, MudaeFarm/Program.cs
Resolves https://github.com/chiyadev/MudaeFarm/issues/135.
MudaeClaimer was refactored significantly.
=> Fix kakera not being claimed without belongs footer

MudaeFarm/MudaeClaimer.cs
Resolves https://github.com/chiyadev/MudaeFarm/issues/141.
=> Ignore cooldown for purple kakera

MudaeFarm/MudaeClaimer.cs, MudaeFarm/MudaeFarm.csproj, MudaeFarm/NotificationSender.cs, MudaeFarm/Options.cs, MudaeFarm/Program.cs, README.md
Please do mind the code, this is my first time touching C#.
I have not tested if it builds properly on other OS as I don't have access to them. 
Resolves #148
=> Add Windows toast notification on character/kakera claim
